name: Release Slack Message
on:
  release:
    types: [published]

jobs:
  send-message:
    name: Send Slack Message for New Release
    runs-on: ubuntu-latest
    steps:
      - name: Run cURL Command
        run: |
          curl -X POST -H 'Content-type: application/json' --data
          '{"text":"METplus ${{ github.event.release.tag_name }} release was created: <${{ github.event.release.html_url }}>"}'
          ${{ secrets.SLACK_WEBHOOK }}